services:
  web:
    build: .
    image: <DOCKER_USERNAME>/<PROJECT_NAME>:latest
    container_name: web
    restart: unless-stopped
    depends_on:
      - db
      - valkey
    env_file:
      - .env
    environment:
      - ORIGIN=http://localhost:4173
      - POSTGRES_HOST=db
      - VALKEY_HOST=valkey
    ports:
      - '4173:3000'

  db:
    image: postgres
    container_name: db
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql:Z
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  valkey:
    container_name: valkey
    image: valkey/valkey
    command: valkey-server --save 60 1 --loglevel warning
    ports:
      - '${VALKEY_PORT:-6379}:6379'
    volumes:
      - valkey-data:/data

volumes:
  valkey-data:
